window.machineConfig = {
  machineId: "tomato-kingdom-reel-preview",
  machineName: "トマト王国 リールプレビュー",
  canvas: {
    width: 1024,
    height: 1536,
  },
  bodyImage: "./assets/symbols/kyoutai.PNG",
  fallbackBackground: {
    top: "#2d1d15",
    bottom: "#7d1f10",
  },
  symbols: [
    { id: "cherry", label: "チェリー", image: "./assets/symbols/cherry.PNG", accent: "#d8342a" },
    { id: "seven", label: "7", image: "./assets/symbols/7.PNG", accent: "#f44336" },
    { id: "bell", label: "ベル", image: "./assets/symbols/BELL.PNG", accent: "#f2c230" },
    { id: "big", label: "BIG", image: "./assets/symbols/BIG.PNG", accent: "#db2d2d" },
    { id: "blue7", label: "青七", image: "./assets/symbols/blue7.PNG", accent: "#2142ff" },
    { id: "suika", label: "スイカ", image: "./assets/symbols/suika.PNG", accent: "#18af43" },
    { id: "reg", label: "REG", image: "./assets/symbols/REG.PNG", accent: "#4a4a4a" },
    { id: "replay", label: "リプレイ", image: "./assets/symbols/Replay.PNG", accent: "#ffe100" },
  ],
  reels: [
    {
      id: "reel-1",
      label: "リール1",
      defaultSymbolId: "bell",
      strip: [
        "replay",
        "bell",
        "big",
        "big",
        "big",
        "replay",
        "bell",
        "cherry",
        "seven",
        "suika",
        "replay",
        "bell",
        "suika",
        "bell",
        "blue7",
        "replay",
        "reg",
        "bell",
        "suika",
        "cherry",
        "seven",
      ],
    },
    {
      id: "reel-2",
      label: "リール2",
      defaultSymbolId: "cherry",
      strip: [
        "suika",
        "cherry",
        "bell",
        "replay",
        "reg",
        "reg",
        "cherry",
        "reg",
        "bell",
        "replay",
        "big",
        "replay",
        "suika",
        "replay",
        "bell",
        "blue7",
        "cherry",
        "bell",
        "replay",
        "seven",
        "cherry",
      ],
    },
    {
      id: "reel-3",
      label: "リール3",
      defaultSymbolId: "blue7",
      strip: [
        "blue7",
        "replay",
        "suika",
        "bell",
        "cherry",
        "replay",
        "suika",
        "bell",
        "big",
        "replay",
        "cherry",
        "bell",
        "reg",
        "replay",
        "suika",
        "bell",
        "cherry",
        "replay",
        "suika",
        "bell",
        "seven",
      ],
    },
  ],
  layout: {
    visibleRows: 3,
    rowGap: 0,
    reelWindows: [
      { x: 244, y: 486, width: 152, height: 202 },
      { x: 436, y: 486, width: 152, height: 202 },
      { x: 628, y: 486, width: 152, height: 202 },
    ],
    symbolInsetX: 3,
    symbolInsetY: 2,
  },
};
